{
  "comments": [
    {
      "key": {
        "uuid": "9e7a001e_4612573b",
        "filename": "openstack-ironic-python-agent.spec",
        "patchSetId": 2
      },
      "lineNbr": 81,
      "author": {
        "id": 78
      },
      "writtenOn": "2021-12-11T18:47:02Z",
      "side": 1,
      "message": "I cannot fetch the logs, but I suspect this may upset RHEL 9",
      "revId": "50db3f9bafdc3209439e481eea825f7d4316764a",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "95762cd9_fd251d18",
        "filename": "openstack-ironic-python-agent.spec",
        "patchSetId": 2
      },
      "lineNbr": 81,
      "author": {
        "id": 558
      },
      "writtenOn": "2021-12-12T19:06:40Z",
      "side": 1,
      "message": "you\u0027re right, I forgot this is not valid for python higher than 3.8",
      "parentUuid": "9e7a001e_4612573b",
      "revId": "50db3f9bafdc3209439e481eea825f7d4316764a",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    }
  ]
}